<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="26.7.0" />
    <PackageReference Include="ReportViewerCore.WinForms" Version="15.1.33" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="StudentGradeSummary.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>StudentGradeSummary.xsd</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Report1.rdlc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="StudentGradeSummary.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>StudentGradeSummary.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>